# Site settings
title: MOSC Blog
email: mosc@lists.berkeley.edu
description:
baseurl: "//moscblog.nicholas-fong.com"
url: "//moscblog.nicholas-fong.com"

github: https://github.com/

paginate: 2
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
